version: "3.9"

services:
  postgres-develop:
    image: postgres:15
    container_name: urbantracker-postgres-develop
    restart: always
    env_file:
      - .env.develop
    ports:
      - "5433:5432"
    networks:
      - network_develop
    volumes:
      - postgres_data_develop:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 30s
      timeout: 10s
      retries: 5

volumes:
  postgres_data_develop:
    driver: local

networks:
  network_develop:
    driver: bridge
