version: "3.9"

services:
  postgres-staging:
    image: postgres:15
    container_name: urbantracker-postgres-staging
    restart: always
    env_file:
      - .env.staging
    ports:
      - "5435:5432"
    networks:
      - network_staging
    volumes:
      - postgres_data_staging:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 30s
      timeout: 10s
      retries: 5

volumes:
  postgres_data_staging:
    driver: local

networks:
  network_staging:
    driver: bridge
