version: "3.9"

services:
  postgres-main:
    image: postgres:15
    container_name: urbantracker-postgres-main
    restart: always
    env_file:
      - .env.main
    ports:
      - "5432:5432"
    networks:
      - network_main
    volumes:
      - postgres_data_main:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 30s
      timeout: 10s
      retries: 5

volumes:
  postgres_data_main:
    driver: local

networks:
  network_main:
    driver: bridge
